Usitec_Usinagem/Models/ContaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Usitec_Usinagem.Models
{
    public class ContaViewModel
    {
        [Required(ErrorMessage = "O campo Nome de Usuário é obrigatório.")]
        public string NomeUsuario { get; set; }
        [Required(ErrorMessage = "O campo Senha é obrigatório.")]
        public string Senha { get; set; }
        [Required(ErrorMessage = "O campo Confirmar Senha é obrigatório.")]
        [Compare("Senha", ErrorMessage = "A senha e a confirmação de senha não correspondem.")]
        public string ConfirmarSenha { get; set; }
    }
}

Usitec_Usinagem/Models/ErrorViewModel.cs
using System;

namespace Usitec_Usinagem.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Usitec_Usinagem/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Usitec_Usinagem.Models
{
    public class LoginViewModel
    {
        public string NomeUsuario { get; set; }
        public string Senha { get; set; }
    }
}

Usitec_Usinagem/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Usitec_Usinagem.Models
{
    
    public class Usuario
    {
        public int Id { get; set; }
        public string NomeUsuario { get; set; }
        public string Senha { get; set; }
    }
}

Usitec_Usinagem/Controllers/ContaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Usitec_Usinagem.Data;
using Usitec_Usinagem.Models;

namespace Usitec_Usinagem.Controllers
{
    public class ContaController : Controller
    {
        private readonly ApplicationDbContext _applicationDbContext;
        
        public ContaController(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
            
        }
        public IActionResult NovaConta()
        {
            return View(new ContaViewModel());
        }

        [HttpPost]
        public IActionResult CriarConta(ContaViewModel contaViewModel)
        {
            if (contaViewModel.Senha == null)
            {
                ModelState.AddModelError("Senha", "A senha não pode ser nula.");
            }

            if (contaViewModel.NomeUsuario == null)
            {
                ModelState.AddModelError("NomeUsuario", "O nome de usuário não pode ser nulo.");
            }

            if(contaViewModel.Senha != contaViewModel.ConfirmarSenha)
            {
                ModelState.AddModelError("confirmarSenha", "A senha e a confirmação de senha não correspondem.");
            }

            
            if (ModelState.IsValid)
            {
               
                var usuario = new Usuario
                {
                    NomeUsuario = contaViewModel.NomeUsuario,
                    Senha = contaViewModel.Senha
                };

                                
                if (usuario != null)
                {
                    _applicationDbContext.Usuarios.Add(usuario);
                    _applicationDbContext.SaveChanges();

                    TempData["MensagemSucesso"] = "Nova conta criada com sucesso!";
                    return RedirectToAction("Login", new { NomeUsuario = contaViewModel.NomeUsuario });
                }
            }
            else
            {
                return View("NovaConta", contaViewModel);
            }

            return View("NovaConta", contaViewModel);
        }

        public IActionResult Login(string nomeUsuario)
        {
            var loginViewModel = new LoginViewModel { NomeUsuario = nomeUsuario };
            return View("~/Views/PaginaLogin/Login.cshtml", loginViewModel);
        }
    }
}

Usitec_Usinagem/Controllers/PaginaInicialController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Usitec_Usinagem.Controllers
{
    public class PaginaInicialController : Controller
    {
        private readonly ILogger<PaginaInicialController> _logger;

        public PaginaInicialController(ILogger<PaginaInicialController> logger)
        {
            _logger = logger;
        }
        public IActionResult Inicio()
        {
            _logger.LogInformation("Inicio da Action Inicio");
            return View();
        }
    }
}

Usitec_Usinagem/Controllers/PaginaLoginController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Usitec_Usinagem.Data;
using Usitec_Usinagem.Models;

namespace Usitec_Usinagem.Controllers
{
    public class PaginaLoginController : Controller
    {
        private readonly ILogger<PaginaLoginController> _logger;
        private readonly ApplicationDbContext _applicationDbContext;

        public PaginaLoginController(ILogger<PaginaLoginController> logger, ApplicationDbContext applicationDbContext)
        {
            _logger = logger;
            _applicationDbContext = applicationDbContext;
        }

        public IActionResult Login()
        {
            Console.WriteLine("Entrou no método LoginViewModel");
            return View(new LoginViewModel());
        }

        [HttpPost]
        public IActionResult Autenticar(LoginViewModel loginViewModel)
        {
            Console.WriteLine("Entrou no método Autenticar");
            var usuario = _applicationDbContext.Usuarios
                .FirstOrDefault(u => u.NomeUsuario == loginViewModel.NomeUsuario && u.Senha == loginViewModel.Senha);

            if (usuario != null)
            {
                Console.WriteLine("Autenticação bem-sucedida. Redirecionando para Inicio");
                return RedirectToAction("Inicio", "PaginaInicial");
            }
            else
            {
                Console.WriteLine("Autenticação falhou. Retornando para a página de Login");
                ModelState.AddModelError(string.Empty, "Nome de usuário ou senha inválidos.");
                return View("Login", loginViewModel);
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Usitec_Usinagem/Views/Conta/NovaConta.cshtml
@{
    ViewData["Title"] = "Criar Nova Conta";
    Layout = "LayoutNovaConta";
    @model Usitec_Usinagem.Models.ContaViewModel;
}

@section content{
<form asp-controller="Conta" asp-action="CriarConta" method="post" asp-for="ContaViewModel">
    <div class="container">
        <div class="info">
            <h1>Olá, Por Favor!</h1>
            <p>Insira o nome completo do funcionário no "Nome de Usúario".</p>
            <p>Crie uma senha fácil de ser memorizada.</p>
        </div>
        <div class="conta-container">
            <h2><img src="~/Imagens/download-removebg-preview.png" width="100" height="100" /></h2>
            <input type="text" id="nomeUsuario" name="NomeUsuario" placeholder="Nome de usuário" asp-for="NomeUsuario"/>
            <input type="password" id="senha" name="Senha" placeholder="Senha" asp-for="Senha"/>
            <input type="password" id="confirmarSenha" name="ConfirmarSenha" placeholder="Confirma Senha" asp-for="ConfirmarSenha"/>
            <button>Criar Conta</button>
        </div>
    </div>
</form>

<div asp-validation-summary="All" class="text-danger"></div>
}

Usitec_Usinagem/Views/PaginaInicial/Inicio.cshtml
@{ 
    ViewData["Title"] = "Página Inicial";
    Layout = "LayoutInicio";
}

@section content{
    <h2>Welcome!</h2>
}

Usitec_Usinagem/Views/PaginaLogin/Login.cshtml
@{
    ViewData["Title"] = "Página de Login";
    Layout = "LayoutLogin";
}

@section content{
    <form asp-controller="PaginaLogin" asp-action="Autenticar" method="post">
    <div class="container">
        <div class="bem-vindo">
            <h1>Bem Vindo!</h1>
            <h2>Usitec Usinagem</h2>
            <p>Uma empresa dedicada a prestar serviços de torno e fresa nos processos convencionais e cnc, usinagem de pequeno e médio porte em materiais ferrosos e não ferrosos.</p>
            <p>Forneceremos o melhor serviço de Usinagem para o seu negócio.</p>
            <p>Fundada em 13 de junho do ano de 2001 diante de uma oportunidade de mercado. </p>
            <p>Desde então a Usitec vem se adaptando as mudanças do mercado e de seus clientes afim de fortalecer cada vez mais suas parcerias.</p>
        </div>
        <div class="login-container">
            <h2><img src="~/Imagens/download-removebg-preview.png" width="100" height="100" /></h2>
            <input type="text" name="NomeUsuario" placeholder="Nome de usuário" />
            <input type="password" name="Senha" placeholder="Senha" />
            <p class="left-align"><a href="#" onclick="console.log('Antes de chamar mostrarPopup'); mostrarPopup('esqueceuSenha')">Esqueceu a senha?</a></p>
            <button>Entrar</button>
            <a asp-controller="Conta" asp-action="NovaConta">Criar nova conta?</a>
        </div>
    </div>
    </form>
}

Usitec_Usinagem/Views/Shared/LayoutInicio.cshtml
<!DOCTYPE html>

<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width", initial-scale="1.0"/>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Inicio.css" />
</head>
<body>
    <div>
        @RenderBody()
        @RenderSection("content", required: false)
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Usitec_Usinagem/Views/Shared/LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width", initial-scale="1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Login.css" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            @RenderSection("content", required: false)
        </main>
    </div>
        
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/Login.js" asp-append-version="true"></script>
</body>
</html>

Usitec_Usinagem/Views/Shared/LayoutNovaConta.cshtml
<!DOCTYPE html>

<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width", initial-scale="1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/NovaConta.css" />
</head>
<body>
    <div>
        @RenderBody()
        @RenderSection("content", required: false)
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>